### ISSUE TITLE
Include a license file

### ISSUE THREAD

**Issue by antznin** [SethBling/cbscript#13] opened 2024-03-11 13:41 UTC
Since this project is free software/open source, it would really benefit from including a license file. Choice of license is of course left to the owner.

Please see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license:

> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work

**Comment by DivergentClouds** [comment] 2024-03-11 16:56
duplicate of #3

**Comment by RustoMCSpit** [comment] 2024-03-11 21:06
close this

**Comment by SethBling** [comment] 2024-03-11 21:31
Duplicate of #3 .

**Closed by SethBling** 2024-03-11 21:31 UTC

**Comment by antznin** [comment] 2024-03-11 22:04
Sorry about this, I missed the duplicate.
